module.exports = {
  "avi": "video/x-msvideo",
  "css": "text/css",
  "eot": "application/vnd.ms-fontobject",
  "flv": "video/x-flv",
  "gif": "image/gif",
  "html": "text/html",
  "ico": "image/x-icon",
  "jpeg": "image/jpeg",
  "jpg": "image/jpeg",
  "js": "text/javascript",
  "json": "application/json",
  "less": "text/css",
  "mp3": "audio/mpeg",
  "mp4": "video/mp4",
  "3gp": "video/3gpp",
  "ogg": "video/ogg",
  "ogv": "video/ogg",
  "webm": "video/webm",
  "m4a": "audio/mp4a-latm",
  "pdf": "application/pdf",
  "png": "image/png",
  "scss": "text/css",
  "svg": "image/svg+xml",
  "swf": "application/x-shockwave-flash",
  "tiff": "image/tiff",
  "txt": "text/plain",
  "ttf": "application/octet-stream",
  "wav": "audio/x-wav",
  "webp": "text/html",
  "wma": "audio/x-ms-wma",
  "wmv": "video/x-ms-wmv",
  "woff": "application/x-font-woff",
  "xml": "text/xml"
};

